[package]
name = "kattis_template"
version = "0.1.0"
authors = ["Viola SÃ¶derlund <violaso@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
